# Fly.io Configuration for Marker Engine
# Deploy with: fly launch --config fly.toml

app = "marker-engine-prod"
primary_region = "fra"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "docker/Dockerfile.production"
  ignorefile = ".dockerignore"

[env]
  ENVIRONMENT = "production"
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false

# Scaling configuration
[metrics]
  port = 9091
  path = "/metrics"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"

# Persistent volumes for file storage
[[mounts]]
  destination = "/data"
  source = "marker_data"